version: "3.8"

services:
  extractor-be:
    build: .
    ports: 
      - "8080:8080"
    environment:
      DB_HOST: extractor-db 
      DB_PORT: 3306
      DB_USERNAME: viettel-user
      DB_PASSWORD: viettel
    depends_on:
      extractor-db:
        condition: service_healthy
    networks:
      - app-network

  extractor-db:
    image: mysql:8.0
    ports: 
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: viettel
      MYSQL_DATABASE: ebdb 
      MYSQL_USER: viettel-user
      MYSQL_PASSWORD: viettel
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - app-network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-p$$MYSQL_ROOT_PASSWORD"]
      interval: 5s
      timeout: 20s
      retries: 10
      start_period: 30s

  carbone:
    image: carbone/carbone-ee
    ports: 
      - "4000:4000"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  mysql-data:
    driver: local
